apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: pv-ns
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/www/html
          name: mypersistenvolume
  volumes:
    - name: mypersistenvolume
      persistentVolumeClaim:
        claimName: my-hostpath-pvc