# 1.1
apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: web-server-container
      image: nginx:1.21
      ports:
        - containerPort: 80
---
#1.2
apiVersion: v1
kind: Pod
metadata:
  name: command-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox-container
      image: busybox
      command:
        - sh
        - -c
        - sleep 3600
      env:
        - name: APP_ENV
          value: "production"
        - name: DEBUG_MODE
          value: "false"
        - name: MAX_CONNECTIONS
          value: "100"

---
#1.3
apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - sh
        - -c
        - sleep 3600
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"