# 2.1
apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: web-content
  volumes:
    - name: web-content
      emptyDir: {}

---
#2.2
apiVersion: v1
kind: Pod
metadata:
  name: busybox-server
spec:
  containers:
    - name: busybox-container
      image: busybox
      command:
        - sh
        - -c
        - sleep 3600
      volumeMounts:
        - mountPath: /host-tmp
          name: host-path-volume
  
  volumes:
    - name: host-path-volume
      hostPath:
        path: /tmp
        type: Directory

---
#2.3
apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/cache/nginx
          name: empty
        - mountPath: /var/log/nginx
          name: host
    
  volumes:
    - name: empty
      emptyDir: {}
    - name: host
      hostPath:
        path: /var/log
        type: Directory

---
