apiVersion: v1
kind: Pod
metadata:
  name: commands-args-pod
spec:
  restartPolicy: Never
  containers:
    - name: nginx-container
      image: nginx:latest
    - name: debian-container
      image: debian
      command: ["sleep"]
      args: ["60"]