apiVersion: v1
kind: Pod
metadata:
  name: init-pod-container
spec:
  restartPolicy: Always
  initContainers:
    - name: preparation-container
      image: busybox
      command:
        - "sh"
        - "-c"
        - "echo Preparing config…; sleep 5"
  containers:
    - name: nginx
      image: nginx:latest
