apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: quota-ns
spec:
  limits:
    - default:
        cpu: 500m
        memory: 256Mi
      defaultRequest:
        cpu: 500m
        memory: 128Mi
      max:
        cpu: "1"
        memory: "1000Mi"
      min:
        cpu: 100m
        memory: 128Mi 
      type: Container
