apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: sidecar
      image: busybox
      command:
        - "sh"
        - "-c"
        - "echo Sidecar running; sleep 3600"

